version: '3'
services:
  order:
    build:
      context: .
      dockerfile: order.Dockerfile
    ports:
      - '3000:3000'
    links:
      - db
      - msg
    environment:
      ORDER_MONGODB_URL: mongodb://db:27017/order
      REDIS_URL: redis://msg:6379
  payment:
    build:
      context: .
      dockerfile: payment.Dockerfile
    links:
      - msg
    environment:
      REDIS_URL: redis://msg:6379
  db:
    image: mongo:3
  msg:
    image: redis:4.0-alpine
